theme = "dracula_at_night"

[editor]

line-number = "absolute"
cursorline = true
cursorcolumn = true
color-modes = true
bufferline = "multiple"
idle-timeout = 0
completion-replace = true


[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal]
# Cycle through buffers with Ctrl-Shift and left/right
C-S-left = ":buffer-next"
C-S-right = ":buffer-previous"

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.statusline]
left = [
  "mode",
 "version-control"
  ]
center = [
  "spinner",
  "file-name"
  ]
right = [
  "file-type",
  "position",
  "diagnostics",
  "selections",
  "file-encoding",
  "file-line-ending"
  ]
separator = "â”‚"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 300000
